<?php

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'settings edit');

$form->prepare();
?>
<?= $this->pageTitle($translate('Settings'), 1, $translate('Admin Addition')) ?>
<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <button type="submit"><?= $translate('Save') ?></button>
</div>

<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag() ?>
