<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'forgot-password');
$lf1url = $this->setting('adminaddon_lf_1_url');
$lf1label = $this->setting('adminaddon_lf_1_label');
$lf2url = $this->setting('adminaddon_lf_2_url');
$lf2label = $this->setting('adminaddon_lf_2_label');
$form->prepare();
?>
<h1><?php echo $translate('Forgot password'); ?></h1>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form, false);
?>
<div class="login-actions">
    <button><?php echo $translate('Send password reset email'); ?></button>
    <button type="button" name="log-in'" onclick="window.location.href='<?= $this->url('login') ?>'" class="button" value=""><?= $translate('Log in') ?></button>
    <button type="button" name="back-to-site" onclick="window.location.href='/'" class="button" value=""><?= $translate('Back to Site') ?></button>
    <?php if(!empty($lf1url) && !empty($lf1label)): ?>
	<button type="button" name="back-to-site" onclick="window.location.href='<?= $lf1url ?>'" class="button" value=""><?= $lf1label ?></button>
	<?php endif; ?>
	<?php if(!empty($lf2url) && !empty($lf2label)): ?>
	<button type="button" name="back-to-site" onclick="window.location.href='<?= $lf2url ?>'" class="button" value=""><?= $lf2label ?></button>
	<?php endif; ?>
</div>
<?php echo $this->form()->closeTag(); ?>
