<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$AdminAddon = $this->AdminAddon();

$isFacetModeDirect = in_array($options['mode'] ?? null, ['link', 'js']);
$displayCount = !empty($options['display_count']);
?>

<?php if(!empty($facetValues)): ?>
<div class="facet-items">
    <?php foreach ($facetValues as $facetValue):
        $facetValue['active'] = False;
        if(!empty($query['property'])){
            $key = $AdminAddon->searchInArray($query['property'], ['property' => $property_id]);
            // , 'text' => $facetValue['value']
        }
        if(!empty($key) && !empty($query['property'][$key[0]]['text'])){
            if($query['property'][$key[0]]['text'] == $facetValue['value']){
                $facetValue['active'] = True;
            }
        }
        if(!empty($query['facets'][$name])){
            if(is_array($query['facets'][$name]) && in_array($facetValue['value'], $query['facets'][$name])){
                $facetValue['active'] = True;
            }elseif(is_string($query['facets'][$name]) && $facetValue['value'] == $query['facets'][$name]){
                $facetValue['active'] = True;
            }       
        }

        $escapedValue = $escapeAttr($facetValue['value']);
        $escapedId = 'facets-'.$name.'-'.$escapedValue;
        $inputName = 'facets['.$name.'][]';
        $label = $displayCount
            ? sprintf('%s <span class="badge bg-secondary ms-1">%d</span>', $escape($facetValue['label']),  $facetValue['count'])
            : $escape($facetValue['label']);
    ?>
    <div class="form-check facet-item <?= $facetValue['active'] ? 'active' : 'inactive' ?>">
        <input class="form-check-input" type="checkbox" name="<?= $inputName ?>" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
        <label class="form-check-label" for="<?= $escapedId ?>"><?= $label ?></label>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>